// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aipw_curve_v2_cpp
List aipw_curve_v2_cpp(List forest, NumericMatrix X_obs, NumericVector y_honest, IntegerVector honest_idx, NumericVector ghat, int var_col, NumericVector grid_points, double sigma2_override);
RcppExport SEXP _infForest_aipw_curve_v2_cpp(SEXP forestSEXP, SEXP X_obsSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP grid_pointsSEXP, SEXP sigma2_overrideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_obs(X_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_points(grid_pointsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_override(sigma2_overrideSEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_curve_v2_cpp(forest, X_obs, y_honest, honest_idx, ghat, var_col, grid_points, sigma2_override));
    return rcpp_result_gen;
END_RCPP
}
// aipw_scores_v2_cpp
List aipw_scores_v2_cpp(List forest, NumericMatrix X_obs, NumericVector y_honest, IntegerVector honest_idx, NumericVector ghat, int var_col, bool is_binary, double a, double b, Nullable<NumericVector> indicator_);
RcppExport SEXP _infForest_aipw_scores_v2_cpp(SEXP forestSEXP, SEXP X_obsSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP is_binarySEXP, SEXP aSEXP, SEXP bSEXP, SEXP indicator_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_obs(X_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< bool >::type is_binary(is_binarySEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type indicator_(indicator_SEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_scores_v2_cpp(forest, X_obs, y_honest, honest_idx, ghat, var_col, is_binary, a, b, indicator_));
    return rcpp_result_gen;
END_RCPP
}
// compute_design_point_variance_cpp
List compute_design_point_variance_cpp(List forest, NumericMatrix X_query, IntegerMatrix train_leaf_ids, IntegerMatrix inbag, NumericVector f_hat_train, bool outcome_binary, int n_threads);
RcppExport SEXP _infForest_compute_design_point_variance_cpp(SEXP forestSEXP, SEXP X_querySEXP, SEXP train_leaf_idsSEXP, SEXP inbagSEXP, SEXP f_hat_trainSEXP, SEXP outcome_binarySEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_query(X_querySEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type train_leaf_ids(train_leaf_idsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type inbag(inbagSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_hat_train(f_hat_trainSEXP);
    Rcpp::traits::input_parameter< bool >::type outcome_binary(outcome_binarySEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_design_point_variance_cpp(forest, X_query, train_leaf_ids, inbag, f_hat_train, outcome_binary, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// precompute_forest_cache_cpp
List precompute_forest_cache_cpp(List forest, NumericMatrix X_obs, NumericVector y_honest, IntegerVector honest_idx);
RcppExport SEXP _infForest_precompute_forest_cache_cpp(SEXP forestSEXP, SEXP X_obsSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_obs(X_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(precompute_forest_cache_cpp(forest, X_obs, y_honest, honest_idx));
    return rcpp_result_gen;
END_RCPP
}
// aipw_scores_cached_cpp
List aipw_scores_cached_cpp(List cache, NumericVector ghat, int var_col, bool is_binary, double a, double b, Nullable<NumericVector> indicator_, int n_threads);
RcppExport SEXP _infForest_aipw_scores_cached_cpp(SEXP cacheSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP is_binarySEXP, SEXP aSEXP, SEXP bSEXP, SEXP indicator_SEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache(cacheSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< bool >::type is_binary(is_binarySEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type indicator_(indicator_SEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_scores_cached_cpp(cache, ghat, var_col, is_binary, a, b, indicator_, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// aipw_scores_multi_cpp
List aipw_scores_multi_cpp(List cache, IntegerVector var_cols, LogicalVector is_binary_vec, NumericVector a_vals, NumericVector b_vals, List ghat_list, Nullable<List> indicator_list_);
RcppExport SEXP _infForest_aipw_scores_multi_cpp(SEXP cacheSEXP, SEXP var_colsSEXP, SEXP is_binary_vecSEXP, SEXP a_valsSEXP, SEXP b_valsSEXP, SEXP ghat_listSEXP, SEXP indicator_list_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache(cacheSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type var_cols(var_colsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_binary_vec(is_binary_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_vals(a_valsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_vals(b_valsSEXP);
    Rcpp::traits::input_parameter< List >::type ghat_list(ghat_listSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type indicator_list_(indicator_list_SEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_scores_multi_cpp(cache, var_cols, is_binary_vec, a_vals, b_vals, ghat_list, indicator_list_));
    return rcpp_result_gen;
END_RCPP
}
// aipw_curve_cached_cpp
List aipw_curve_cached_cpp(List cache, NumericVector ghat, int var_col, NumericVector grid_points, double sigma2_override, int n_threads);
RcppExport SEXP _infForest_aipw_curve_cached_cpp(SEXP cacheSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP grid_pointsSEXP, SEXP sigma2_overrideSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache(cacheSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_points(grid_pointsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_override(sigma2_overrideSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_curve_cached_cpp(cache, ghat, var_col, grid_points, sigma2_override, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// honest_predict_cached_cpp
NumericVector honest_predict_cached_cpp(List cache, NumericMatrix X_query, int n_threads);
RcppExport SEXP _infForest_honest_predict_cached_cpp(SEXP cacheSEXP, SEXP X_querySEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache(cacheSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_query(X_querySEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_predict_cached_cpp(cache, X_query, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// honest_predict_cpp
NumericVector honest_predict_cpp(List forest, NumericMatrix X_query, NumericMatrix X_honest, NumericVector y_honest, IntegerVector honest_idx);
RcppExport SEXP _infForest_honest_predict_cpp(SEXP forestSEXP, SEXP X_querySEXP, SEXP X_honestSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_query(X_querySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_honest(X_honestSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_predict_cpp(forest, X_query, X_honest, y_honest, honest_idx));
    return rcpp_result_gen;
END_RCPP
}
// pasr_extract_all_marginal_cpp
NumericMatrix pasr_extract_all_marginal_cpp(List cache_list, List Y_syn_list, List X_cf_list, NumericMatrix omega_mat, int n_threads);
RcppExport SEXP _infForest_pasr_extract_all_marginal_cpp(SEXP cache_listSEXP, SEXP Y_syn_listSEXP, SEXP X_cf_listSEXP, SEXP omega_matSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache_list(cache_listSEXP);
    Rcpp::traits::input_parameter< List >::type Y_syn_list(Y_syn_listSEXP);
    Rcpp::traits::input_parameter< List >::type X_cf_list(X_cf_listSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type omega_mat(omega_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pasr_extract_all_marginal_cpp(cache_list, Y_syn_list, X_cf_list, omega_mat, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pasr_extract_all_level_curve_cpp
NumericMatrix pasr_extract_all_level_curve_cpp(List cache_list, List Y_syn_list, NumericVector ghat, NumericVector x_var, int var_col, NumericVector grid_points, int n_threads);
RcppExport SEXP _infForest_pasr_extract_all_level_curve_cpp(SEXP cache_listSEXP, SEXP Y_syn_listSEXP, SEXP ghatSEXP, SEXP x_varSEXP, SEXP var_colSEXP, SEXP grid_pointsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache_list(cache_listSEXP);
    Rcpp::traits::input_parameter< List >::type Y_syn_list(Y_syn_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_var(x_varSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_points(grid_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pasr_extract_all_level_curve_cpp(cache_list, Y_syn_list, ghat, x_var, var_col, grid_points, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_infForest_aipw_curve_v2_cpp", (DL_FUNC) &_infForest_aipw_curve_v2_cpp, 8},
    {"_infForest_aipw_scores_v2_cpp", (DL_FUNC) &_infForest_aipw_scores_v2_cpp, 10},
    {"_infForest_compute_design_point_variance_cpp", (DL_FUNC) &_infForest_compute_design_point_variance_cpp, 7},
    {"_infForest_precompute_forest_cache_cpp", (DL_FUNC) &_infForest_precompute_forest_cache_cpp, 4},
    {"_infForest_aipw_scores_cached_cpp", (DL_FUNC) &_infForest_aipw_scores_cached_cpp, 8},
    {"_infForest_aipw_scores_multi_cpp", (DL_FUNC) &_infForest_aipw_scores_multi_cpp, 7},
    {"_infForest_aipw_curve_cached_cpp", (DL_FUNC) &_infForest_aipw_curve_cached_cpp, 6},
    {"_infForest_honest_predict_cached_cpp", (DL_FUNC) &_infForest_honest_predict_cached_cpp, 3},
    {"_infForest_honest_predict_cpp", (DL_FUNC) &_infForest_honest_predict_cpp, 5},
    {"_infForest_pasr_extract_all_marginal_cpp", (DL_FUNC) &_infForest_pasr_extract_all_marginal_cpp, 5},
    {"_infForest_pasr_extract_all_level_curve_cpp", (DL_FUNC) &_infForest_pasr_extract_all_level_curve_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_infForest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
