// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// honest_all
List honest_all(List forest, NumericMatrix X_num, NumericVector y_honest, IntegerVector honest_idx, IntegerVector bin_cols, IntegerVector cont_cols, NumericVector cont_thresh, bool per_leaf_denom);
RcppExport SEXP _infForest_honest_all(SEXP forestSEXP, SEXP X_numSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP bin_colsSEXP, SEXP cont_colsSEXP, SEXP cont_threshSEXP, SEXP per_leaf_denomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_num(X_numSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bin_cols(bin_colsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cont_cols(cont_colsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cont_thresh(cont_threshSEXP);
    Rcpp::traits::input_parameter< bool >::type per_leaf_denom(per_leaf_denomSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_all(forest, X_num, y_honest, honest_idx, bin_cols, cont_cols, cont_thresh, per_leaf_denom));
    return rcpp_result_gen;
END_RCPP
}
// honest_curve
List honest_curve(List forest, NumericMatrix X_num, NumericVector y_honest, IntegerVector honest_idx, int col, NumericVector midpoints, NumericVector window_lo, NumericVector window_hi);
RcppExport SEXP _infForest_honest_curve(SEXP forestSEXP, SEXP X_numSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP colSEXP, SEXP midpointsSEXP, SEXP window_loSEXP, SEXP window_hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_num(X_numSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< int >::type col(colSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type midpoints(midpointsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type window_lo(window_loSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type window_hi(window_hiSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_curve(forest, X_num, y_honest, honest_idx, col, midpoints, window_lo, window_hi));
    return rcpp_result_gen;
END_RCPP
}
// honest_interaction_2x2
List honest_interaction_2x2(List forest, NumericMatrix X_num, NumericVector y_honest, IntegerVector honest_idx, int bin_col, int cont_col, double cont_thresh);
RcppExport SEXP _infForest_honest_interaction_2x2(SEXP forestSEXP, SEXP X_numSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP bin_colSEXP, SEXP cont_colSEXP, SEXP cont_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_num(X_numSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< int >::type bin_col(bin_colSEXP);
    Rcpp::traits::input_parameter< int >::type cont_col(cont_colSEXP);
    Rcpp::traits::input_parameter< double >::type cont_thresh(cont_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_interaction_2x2(forest, X_num, y_honest, honest_idx, bin_col, cont_col, cont_thresh));
    return rcpp_result_gen;
END_RCPP
}
// honest_predict_contrast
List honest_predict_contrast(List forest, NumericMatrix X_num, NumericVector y_honest, IntegerVector honest_idx, IntegerVector cont_cols, NumericVector cont_va, NumericVector cont_vb);
RcppExport SEXP _infForest_honest_predict_contrast(SEXP forestSEXP, SEXP X_numSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP cont_colsSEXP, SEXP cont_vaSEXP, SEXP cont_vbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_num(X_numSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cont_cols(cont_colsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cont_va(cont_vaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cont_vb(cont_vbSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_predict_contrast(forest, X_num, y_honest, honest_idx, cont_cols, cont_va, cont_vb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_infForest_honest_all", (DL_FUNC) &_infForest_honest_all, 8},
    {"_infForest_honest_curve", (DL_FUNC) &_infForest_honest_curve, 8},
    {"_infForest_honest_interaction_2x2", (DL_FUNC) &_infForest_honest_interaction_2x2, 7},
    {"_infForest_honest_predict_contrast", (DL_FUNC) &_infForest_honest_predict_contrast, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_infForest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
