// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// precompute_forest_cache_cpp
List precompute_forest_cache_cpp(List forest, NumericMatrix X_obs, NumericVector y_honest, IntegerVector honest_idx);
RcppExport SEXP _infForest_precompute_forest_cache_cpp(SEXP forestSEXP, SEXP X_obsSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_obs(X_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(precompute_forest_cache_cpp(forest, X_obs, y_honest, honest_idx));
    return rcpp_result_gen;
END_RCPP
}
// aipw_scores_cached_cpp
List aipw_scores_cached_cpp(List cache, NumericVector ghat, int var_col, bool is_binary, double a, double b, Nullable<NumericVector> indicator_);
RcppExport SEXP _infForest_aipw_scores_cached_cpp(SEXP cacheSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP is_binarySEXP, SEXP aSEXP, SEXP bSEXP, SEXP indicator_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache(cacheSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< bool >::type is_binary(is_binarySEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type indicator_(indicator_SEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_scores_cached_cpp(cache, ghat, var_col, is_binary, a, b, indicator_));
    return rcpp_result_gen;
END_RCPP
}
// aipw_scores_multi_cpp
List aipw_scores_multi_cpp(List cache, IntegerVector var_cols, LogicalVector is_binary_vec, NumericVector a_vals, NumericVector b_vals, List ghat_list, Nullable<List> indicator_list_);
RcppExport SEXP _infForest_aipw_scores_multi_cpp(SEXP cacheSEXP, SEXP var_colsSEXP, SEXP is_binary_vecSEXP, SEXP a_valsSEXP, SEXP b_valsSEXP, SEXP ghat_listSEXP, SEXP indicator_list_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache(cacheSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type var_cols(var_colsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_binary_vec(is_binary_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_vals(a_valsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_vals(b_valsSEXP);
    Rcpp::traits::input_parameter< List >::type ghat_list(ghat_listSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type indicator_list_(indicator_list_SEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_scores_multi_cpp(cache, var_cols, is_binary_vec, a_vals, b_vals, ghat_list, indicator_list_));
    return rcpp_result_gen;
END_RCPP
}
// aipw_curve_cached_cpp
List aipw_curve_cached_cpp(List cache, NumericVector ghat, int var_col, NumericVector grid_points, double sigma2_override);
RcppExport SEXP _infForest_aipw_curve_cached_cpp(SEXP cacheSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP grid_pointsSEXP, SEXP sigma2_overrideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache(cacheSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_points(grid_pointsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_override(sigma2_overrideSEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_curve_cached_cpp(cache, ghat, var_col, grid_points, sigma2_override));
    return rcpp_result_gen;
END_RCPP
}
// honest_predict_cpp
NumericVector honest_predict_cpp(List forest, NumericMatrix X_query, NumericMatrix X_honest, NumericVector y_honest, IntegerVector honest_idx);
RcppExport SEXP _infForest_honest_predict_cpp(SEXP forestSEXP, SEXP X_querySEXP, SEXP X_honestSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_query(X_querySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_honest(X_honestSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_predict_cpp(forest, X_query, X_honest, y_honest, honest_idx));
    return rcpp_result_gen;
END_RCPP
}
// honest_predict_loo_cpp
NumericVector honest_predict_loo_cpp(List forest, NumericMatrix X_honest, NumericVector y_honest, IntegerVector honest_idx);
RcppExport SEXP _infForest_honest_predict_loo_cpp(SEXP forestSEXP, SEXP X_honestSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_honest(X_honestSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_predict_loo_cpp(forest, X_honest, y_honest, honest_idx));
    return rcpp_result_gen;
END_RCPP
}
// aipw_scores_cpp
List aipw_scores_cpp(List forest, NumericMatrix X_obs, NumericMatrix X_query_a, NumericMatrix X_query_b, NumericVector y_honest, IntegerVector honest_idx, NumericVector ghat, int var_col, bool is_binary, double a, double b);
RcppExport SEXP _infForest_aipw_scores_cpp(SEXP forestSEXP, SEXP X_obsSEXP, SEXP X_query_aSEXP, SEXP X_query_bSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP is_binarySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_obs(X_obsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_query_a(X_query_aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_query_b(X_query_bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< bool >::type is_binary(is_binarySEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_scores_cpp(forest, X_obs, X_query_a, X_query_b, y_honest, honest_idx, ghat, var_col, is_binary, a, b));
    return rcpp_result_gen;
END_RCPP
}
// aipw_scores_v2_cpp
List aipw_scores_v2_cpp(List forest, NumericMatrix X_obs, NumericVector y_honest, IntegerVector honest_idx, NumericVector ghat, int var_col, bool is_binary, double a, double b, Nullable<NumericVector> indicator_);
RcppExport SEXP _infForest_aipw_scores_v2_cpp(SEXP forestSEXP, SEXP X_obsSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP is_binarySEXP, SEXP aSEXP, SEXP bSEXP, SEXP indicator_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_obs(X_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< bool >::type is_binary(is_binarySEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type indicator_(indicator_SEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_scores_v2_cpp(forest, X_obs, y_honest, honest_idx, ghat, var_col, is_binary, a, b, indicator_));
    return rcpp_result_gen;
END_RCPP
}
// aipw_curve_v2_cpp
List aipw_curve_v2_cpp(List forest, NumericMatrix X_obs, NumericVector y_honest, IntegerVector honest_idx, NumericVector ghat, int var_col, NumericVector grid_points, double sigma2_override);
RcppExport SEXP _infForest_aipw_curve_v2_cpp(SEXP forestSEXP, SEXP X_obsSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP grid_pointsSEXP, SEXP sigma2_overrideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_obs(X_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_points(grid_pointsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_override(sigma2_overrideSEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_curve_v2_cpp(forest, X_obs, y_honest, honest_idx, ghat, var_col, grid_points, sigma2_override));
    return rcpp_result_gen;
END_RCPP
}
// aipw_curve_cpp
List aipw_curve_cpp(List forest, NumericMatrix X_obs, List X_grid_list, NumericVector y_honest, IntegerVector honest_idx, NumericVector ghat, int var_col, NumericVector grid_points, double sigma2_override);
RcppExport SEXP _infForest_aipw_curve_cpp(SEXP forestSEXP, SEXP X_obsSEXP, SEXP X_grid_listSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP grid_pointsSEXP, SEXP sigma2_overrideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_obs(X_obsSEXP);
    Rcpp::traits::input_parameter< List >::type X_grid_list(X_grid_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_points(grid_pointsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_override(sigma2_overrideSEXP);
    rcpp_result_gen = Rcpp::wrap(aipw_curve_cpp(forest, X_obs, X_grid_list, y_honest, honest_idx, ghat, var_col, grid_points, sigma2_override));
    return rcpp_result_gen;
END_RCPP
}
// debug_compare_scorers
List debug_compare_scorers(List cache, List forest, NumericMatrix X_obs, NumericVector y_honest, IntegerVector honest_idx, NumericVector ghat, int var_col, double val_a, double val_b, int check_tree);
RcppExport SEXP _infForest_debug_compare_scorers(SEXP cacheSEXP, SEXP forestSEXP, SEXP X_obsSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP ghatSEXP, SEXP var_colSEXP, SEXP val_aSEXP, SEXP val_bSEXP, SEXP check_treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache(cacheSEXP);
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_obs(X_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< double >::type val_a(val_aSEXP);
    Rcpp::traits::input_parameter< double >::type val_b(val_bSEXP);
    Rcpp::traits::input_parameter< int >::type check_tree(check_treeSEXP);
    rcpp_result_gen = Rcpp::wrap(debug_compare_scorers(cache, forest, X_obs, y_honest, honest_idx, ghat, var_col, val_a, val_b, check_tree));
    return rcpp_result_gen;
END_RCPP
}
// debug_tree_walk
List debug_tree_walk(List cache, int var_col, double val_a, double val_b, int tree_idx, int obs_idx);
RcppExport SEXP _infForest_debug_tree_walk(SEXP cacheSEXP, SEXP var_colSEXP, SEXP val_aSEXP, SEXP val_bSEXP, SEXP tree_idxSEXP, SEXP obs_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cache(cacheSEXP);
    Rcpp::traits::input_parameter< int >::type var_col(var_colSEXP);
    Rcpp::traits::input_parameter< double >::type val_a(val_aSEXP);
    Rcpp::traits::input_parameter< double >::type val_b(val_bSEXP);
    Rcpp::traits::input_parameter< int >::type tree_idx(tree_idxSEXP);
    Rcpp::traits::input_parameter< int >::type obs_idx(obs_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(debug_tree_walk(cache, var_col, val_a, val_b, tree_idx, obs_idx));
    return rcpp_result_gen;
END_RCPP
}
// honest_all
List honest_all(List forest, NumericMatrix X_num, NumericVector y_honest, IntegerVector honest_idx, IntegerVector bin_cols, IntegerVector cont_cols, NumericVector cont_thresh, bool per_leaf_denom);
RcppExport SEXP _infForest_honest_all(SEXP forestSEXP, SEXP X_numSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP bin_colsSEXP, SEXP cont_colsSEXP, SEXP cont_threshSEXP, SEXP per_leaf_denomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_num(X_numSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bin_cols(bin_colsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cont_cols(cont_colsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cont_thresh(cont_threshSEXP);
    Rcpp::traits::input_parameter< bool >::type per_leaf_denom(per_leaf_denomSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_all(forest, X_num, y_honest, honest_idx, bin_cols, cont_cols, cont_thresh, per_leaf_denom));
    return rcpp_result_gen;
END_RCPP
}
// honest_curve
List honest_curve(List forest, NumericMatrix X_num, NumericVector y_honest, IntegerVector honest_idx, int col, NumericVector midpoints, NumericVector window_lo, NumericVector window_hi);
RcppExport SEXP _infForest_honest_curve(SEXP forestSEXP, SEXP X_numSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP colSEXP, SEXP midpointsSEXP, SEXP window_loSEXP, SEXP window_hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_num(X_numSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< int >::type col(colSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type midpoints(midpointsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type window_lo(window_loSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type window_hi(window_hiSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_curve(forest, X_num, y_honest, honest_idx, col, midpoints, window_lo, window_hi));
    return rcpp_result_gen;
END_RCPP
}
// honest_interaction_2x2
List honest_interaction_2x2(List forest, NumericMatrix X_num, NumericVector y_honest, IntegerVector honest_idx, int bin_col, int cont_col, double cont_thresh);
RcppExport SEXP _infForest_honest_interaction_2x2(SEXP forestSEXP, SEXP X_numSEXP, SEXP y_honestSEXP, SEXP honest_idxSEXP, SEXP bin_colSEXP, SEXP cont_colSEXP, SEXP cont_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_num(X_numSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_honest(y_honestSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type honest_idx(honest_idxSEXP);
    Rcpp::traits::input_parameter< int >::type bin_col(bin_colSEXP);
    Rcpp::traits::input_parameter< int >::type cont_col(cont_colSEXP);
    Rcpp::traits::input_parameter< double >::type cont_thresh(cont_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(honest_interaction_2x2(forest, X_num, y_honest, honest_idx, bin_col, cont_col, cont_thresh));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_infForest_precompute_forest_cache_cpp", (DL_FUNC) &_infForest_precompute_forest_cache_cpp, 4},
    {"_infForest_aipw_scores_cached_cpp", (DL_FUNC) &_infForest_aipw_scores_cached_cpp, 7},
    {"_infForest_aipw_scores_multi_cpp", (DL_FUNC) &_infForest_aipw_scores_multi_cpp, 7},
    {"_infForest_aipw_curve_cached_cpp", (DL_FUNC) &_infForest_aipw_curve_cached_cpp, 5},
    {"_infForest_honest_predict_cpp", (DL_FUNC) &_infForest_honest_predict_cpp, 5},
    {"_infForest_honest_predict_loo_cpp", (DL_FUNC) &_infForest_honest_predict_loo_cpp, 4},
    {"_infForest_aipw_scores_cpp", (DL_FUNC) &_infForest_aipw_scores_cpp, 11},
    {"_infForest_aipw_scores_v2_cpp", (DL_FUNC) &_infForest_aipw_scores_v2_cpp, 10},
    {"_infForest_aipw_curve_v2_cpp", (DL_FUNC) &_infForest_aipw_curve_v2_cpp, 8},
    {"_infForest_aipw_curve_cpp", (DL_FUNC) &_infForest_aipw_curve_cpp, 9},
    {"_infForest_debug_compare_scorers", (DL_FUNC) &_infForest_debug_compare_scorers, 10},
    {"_infForest_debug_tree_walk", (DL_FUNC) &_infForest_debug_tree_walk, 6},
    {"_infForest_honest_all", (DL_FUNC) &_infForest_honest_all, 8},
    {"_infForest_honest_curve", (DL_FUNC) &_infForest_honest_curve, 8},
    {"_infForest_honest_interaction_2x2", (DL_FUNC) &_infForest_honest_interaction_2x2, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_infForest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
