# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

honest_all <- function(forest, X_num, y_honest, honest_idx, bin_cols, cont_cols, cont_thresh, per_leaf_denom = TRUE, cont_fhat_ref = NULL) {
    .Call(`_infForest_honest_all`, forest, X_num, y_honest, honest_idx, bin_cols, cont_cols, cont_thresh, per_leaf_denom, cont_fhat_ref)
}

honest_curve <- function(forest, X_num, y_honest, honest_idx, col, midpoints, window_lo, window_hi, fhat_ref_vec = NULL) {
    .Call(`_infForest_honest_curve`, forest, X_num, y_honest, honest_idx, col, midpoints, window_lo, window_hi, fhat_ref_vec)
}

honest_interaction_2x2 <- function(forest, X_num, y_honest, honest_idx, bin_col, cont_col, cont_thresh) {
    .Call(`_infForest_honest_interaction_2x2`, forest, X_num, y_honest, honest_idx, bin_col, cont_col, cont_thresh)
}

