# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

honest_predict_cpp <- function(forest, X_query, X_honest, y_honest, honest_idx) {
    .Call(`_infForest_honest_predict_cpp`, forest, X_query, X_honest, y_honest, honest_idx)
}

aipw_scores_cpp <- function(forest, X_obs, X_query_a, X_query_b, y_honest, honest_idx, ghat, var_col, is_binary, a, b) {
    .Call(`_infForest_aipw_scores_cpp`, forest, X_obs, X_query_a, X_query_b, y_honest, honest_idx, ghat, var_col, is_binary, a, b)
}

aipw_curve_cpp <- function(forest, X_obs, X_grid_list, y_honest, honest_idx, ghat, var_col, grid_points) {
    .Call(`_infForest_aipw_curve_cpp`, forest, X_obs, X_grid_list, y_honest, honest_idx, ghat, var_col, grid_points)
}

