# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aipw_curve_v2_cpp <- function(forest, X_obs, y_honest, honest_idx, ghat, var_col, grid_points, sigma2_override = -1.0) {
    .Call(`_infForest_aipw_curve_v2_cpp`, forest, X_obs, y_honest, honest_idx, ghat, var_col, grid_points, sigma2_override)
}

aipw_scores_v2_cpp <- function(forest, X_obs, y_honest, honest_idx, ghat, var_col, is_binary, a, b, indicator_ = NULL) {
    .Call(`_infForest_aipw_scores_v2_cpp`, forest, X_obs, y_honest, honest_idx, ghat, var_col, is_binary, a, b, indicator_)
}

compute_design_point_variance_cpp <- function(forest, X_query, train_leaf_ids, inbag, f_hat_train, outcome_binary, n_threads) {
    .Call(`_infForest_compute_design_point_variance_cpp`, forest, X_query, train_leaf_ids, inbag, f_hat_train, outcome_binary, n_threads)
}

precompute_forest_cache_cpp <- function(forest, X_obs, y_honest, honest_idx) {
    .Call(`_infForest_precompute_forest_cache_cpp`, forest, X_obs, y_honest, honest_idx)
}

aipw_scores_cached_cpp <- function(cache, ghat, var_col, is_binary, a, b, indicator_ = NULL, n_threads = 1L) {
    .Call(`_infForest_aipw_scores_cached_cpp`, cache, ghat, var_col, is_binary, a, b, indicator_, n_threads)
}

aipw_scores_multi_cpp <- function(cache, var_cols, is_binary_vec, a_vals, b_vals, ghat_list, indicator_list_ = NULL) {
    .Call(`_infForest_aipw_scores_multi_cpp`, cache, var_cols, is_binary_vec, a_vals, b_vals, ghat_list, indicator_list_)
}

aipw_curve_cached_cpp <- function(cache, ghat, var_col, grid_points, sigma2_override = -1.0, n_threads = 1L) {
    .Call(`_infForest_aipw_curve_cached_cpp`, cache, ghat, var_col, grid_points, sigma2_override, n_threads)
}

honest_predict_cached_cpp <- function(cache, X_query, n_threads = 1L) {
    .Call(`_infForest_honest_predict_cached_cpp`, cache, X_query, n_threads)
}

honest_predict_cpp <- function(forest, X_query, X_honest, y_honest, honest_idx) {
    .Call(`_infForest_honest_predict_cpp`, forest, X_query, X_honest, y_honest, honest_idx)
}

pasr_extract_all_marginal_cpp <- function(cache_list, Y_syn_list, X_cf_list, omega_mat, n_threads = 1L) {
    .Call(`_infForest_pasr_extract_all_marginal_cpp`, cache_list, Y_syn_list, X_cf_list, omega_mat, n_threads)
}

pasr_extract_all_level_curve_cpp <- function(cache_list, Y_syn_list, ghat, x_var, var_col, grid_points, n_threads = 1L) {
    .Call(`_infForest_pasr_extract_all_level_curve_cpp`, cache_list, Y_syn_list, ghat, x_var, var_col, grid_points, n_threads)
}

